#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#

bindkey "^P" history-beginning-search-backward
bindkey "^N" history-beginning-search-forward

export EDITOR=vim

# ignore directories that start with WINDIR

# http://zshwiki.org/home/scripting/array
# http://zshwiki.org/home/scripting/paramflags#jflag

WINDIR=`cygpath -W`

local -a included_paths=()
local -a excluded_paths=()

for entry in $path[@];
do
	case $entry:u in 
		(${WINDIR:u}*) excluded_paths+=( $entry ); continue
	esac

	included_paths+=( $entry )
done
export PATH=${(j_:_)included_paths}
